import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
const root = process.cwd();
const dist = path.join(root, "dist");
await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
await cp(path.join(root, "site"), dist, { recursive: true });
const e = process.env;
const url = e.SUPABASE_URL || "";
const key = e.SUPABASE_PUBLISHABLE_KEY || "";
const config = `window.FRUITMARKET_SUPABASE_CONFIG = Object.freeze({\n  enabled: ${Boolean(url && key)},\n  url: ${JSON.stringify(url)},\n  publishableKey: ${JSON.stringify(key)},\n  functionsBaseUrl: ${JSON.stringify(url ? `${url}/functions/v1` : "")},\n  siteUrl: ${JSON.stringify(e.FRUITMARKET_SITE_URL || "https://fruit-market.netlify.app")},\n  paymentsEnabled: ${e.FRUITMARKET_PAYMENTS_ENABLED === "true"},\n  settlementsEnabled: ${e.FRUITMARKET_SETTLEMENTS_ENABLED === "true"}\n});\n`;
await writeFile(path.join(dist, "config", "supabase-config.js"), config, "utf8");
console.log(`Built ${dist}`);
