-- 푸릇마켓 Part 44 기본 스키마
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'consumer' check (role in ('consumer','seller','admin')),
  status text not null default 'active' check (status in ('active','suspended','withdrawn')),
  display_name text not null default '',
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.business_information (
  id smallint primary key default 1 check (id = 1),
  brand_name text not null,
  legal_name text not null,
  representative_name text not null,
  registration_number text not null,
  ecommerce_registration_number text not null,
  public_business_address text not null,
  customer_service_phone text,
  customer_service_email text,
  reported_domain text,
  reported_categories text,
  updated_at timestamptz not null default now()
);

create table if not exists public.sellers (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete restrict,
  store_name text not null,
  representative_name text not null,
  business_number text not null unique,
  business_address text not null,
  customer_service_phone text,
  customer_service_email text,
  approval_status text not null default 'PENDING' check (approval_status in ('PENDING','APPROVED','REJECTED')),
  status text not null default 'ACTIVE' check (status in ('ACTIVE','SUSPENDED','CLOSED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seller_applications (
  id uuid primary key default gen_random_uuid(),
  application_number text not null unique default ('SA-' || to_char(now(),'YYYYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),
  user_id uuid references public.profiles(id) on delete set null,
  applicant_email text not null,
  applicant_name text not null,
  phone text not null,
  store_name text not null,
  business_number text not null,
  business_address text not null,
  status text not null default 'PENDING' check (status in ('PENDING','APPROVED','REJECTED','WITHDRAWN')),
  rejection_reason text,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles(id)
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  icon_key text,
  icon_url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.banners (
  id uuid primary key default gen_random_uuid(),
  placement text not null default 'HOME_HERO',
  title text not null,
  image_url text not null,
  link_url text,
  active boolean not null default true,
  sort_order integer not null default 0,
  starts_at timestamptz,
  ends_at timestamptz,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint valid_banner_period check (ends_at is null or starts_at is null or ends_at > starts_at)
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.sellers(id) on delete restrict,
  category_id bigint references public.categories(id) on delete set null,
  slug text not null unique,
  name text not null,
  short_description text not null default '',
  description text not null default '',
  sale_price bigint not null check (sale_price > 0),
  list_price bigint check (list_price is null or list_price >= sale_price),
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  reserved_stock integer not null default 0 check (reserved_stock >= 0 and reserved_stock <= stock_quantity),
  origin text not null default '',
  brix numeric(5,2),
  free_shipping boolean not null default false,
  today_shipping boolean not null default false,
  primary_image_url text,
  sale_status text not null default 'DRAFT' check (sale_status in ('DRAFT','PENDING_APPROVAL','ON_SALE','SOLD_OUT','STOPPED')),
  approval_status text not null default 'PENDING' check (approval_status in ('PENDING','APPROVED','REJECTED')),
  active boolean not null default true,
  version bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists products_public_idx on public.products(active, sale_status, approval_status, updated_at desc);
create index if not exists products_seller_idx on public.products(seller_id, updated_at desc);

create table if not exists public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  image_url text not null,
  alt_text text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.product_options (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  sku text not null unique,
  option_name text not null,
  additional_price bigint not null default 0,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.home_products (
  product_id uuid primary key references public.products(id) on delete cascade,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  address_name text not null default '배송지',
  recipient_name text not null,
  recipient_phone text not null,
  postal_code text not null check (postal_code ~ '^[0-9]{5}$'),
  road_address text not null,
  detail_address text not null default '',
  jibun_address text,
  building_name text,
  delivery_memo text,
  address_search_provider text not null default 'KAKAO_POSTCODE',
  address_selected_at timestamptz not null default now(),
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists one_default_address_per_user on public.addresses(user_id) where is_default;

create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table if not exists public.carts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.cart_items (
  id uuid primary key default gen_random_uuid(),
  cart_id uuid not null references public.carts(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete restrict,
  option_id uuid references public.product_options(id) on delete restrict,
  quantity integer not null check (quantity > 0 and quantity <= 999),
  selected boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(cart_id, product_id, option_id)
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default ('FM-' || to_char(now(),'YYYYMMDDHH24MISS') || '-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,6))),
  buyer_id uuid references public.profiles(id) on delete set null,
  status text not null default 'PENDING_PAYMENT',
  product_total bigint not null default 0,
  shipping_total bigint not null default 0,
  discount_total bigint not null default 0,
  paid_total bigint not null default 0,
  recipient_name text not null,
  recipient_phone text not null,
  postal_code text not null,
  road_address text not null,
  detail_address text not null default '',
  delivery_memo text,
  payment_provider text,
  payment_key text unique,
  ordered_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  seller_id uuid not null references public.sellers(id) on delete restrict,
  product_name text not null,
  option_name text,
  unit_price bigint not null,
  quantity integer not null check (quantity > 0),
  item_total bigint generated always as (unit_price * quantity) stored,
  status text not null default 'PENDING_PAYMENT'
);

create table if not exists public.claims (
  id uuid primary key default gen_random_uuid(),
  order_item_id uuid not null references public.order_items(id) on delete restrict,
  requester_id uuid not null references public.profiles(id) on delete restrict,
  claim_type text not null check (claim_type in ('CANCEL','RETURN','EXCHANGE')),
  reason_code text not null,
  reason_detail text,
  quantity integer not null check (quantity > 0),
  status text not null default 'REQUESTED',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  order_item_id uuid references public.order_items(id) on delete set null,
  rating smallint not null check (rating between 1 and 5),
  content text not null,
  status text not null default 'PENDING' check (status in ('PENDING','PUBLISHED','HIDDEN')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, order_item_id)
);

create table if not exists public.policies (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  title text not null,
  version text not null,
  content text not null,
  content_hash text not null,
  required boolean not null default true,
  published boolean not null default false,
  effective_at timestamptz,
  created_at timestamptz not null default now(),
  unique(code, version)
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  title text not null,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.search_keywords (
  keyword text primary key,
  search_count bigint not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated always as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  reason text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
