import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const read=(rel)=>fs.readFileSync(path.join(root,rel),"utf8");
const exists=(rel)=>fs.existsSync(path.join(root,rel));
const html=read("site/index.html");
const adapter=read("site/assets/js/supabase-adapter.js");
const ui=read("site/assets/js/full-function-ui.js");
const marketplaceUi=read("site/assets/js/marketplace-platform-ui.js");
const protectionUi=read("site/assets/js/mutual-protection-ui.js");
const build=read("scripts/build.mjs");
const config=read("site/config/supabase-config.js");
const api=read("supabase/functions/api/index.ts");
const paymentConfirm=read("supabase/functions/payment-confirm/index.ts");
const paymentCancel=read("supabase/functions/payment-cancel/index.ts");
const checkout=read("supabase/functions/checkout-prepare/index.ts");
const payout=read("supabase/functions/payout-run/index.ts");
const scheduled=read("supabase/functions/scheduled-jobs/index.ts");
const protectionSql=read("supabase/sql/19_mutual_fraud_and_abuse_protection.sql");
const terms=read("site/policies/terms.html");
const privacy=read("site/policies/privacy.html");
const sellerPolicy=read("site/policies/seller.html");
const commerce=read("site/policies/commerce.html");
const trustPolicy=read("site/policies/trust-safety.html");
const failures=[];const checks={};
function check(name,ok){checks[name]=Boolean(ok);if(!ok)failures.push(name)}
const countFiles=dir=>exists(dir)?fs.readdirSync(path.join(root,dir)).filter(n=>fs.statSync(path.join(root,dir,n)).isFile()).length:0;

check("Part48 build marker",html.includes("48.0.0")&&api.includes('buildVersion: "48.0.0"')&&build.includes('version: "48.0.0"'));
check("세부 호수 제거",!html.includes("606호")&&!read("supabase/sql/05_seed_public_data.sql").includes("606호"));
check("사업자 공개주소 건물까지만 유지",html.includes("엄궁북로 62, 204동"));
check("배너 3장 파일",countFiles("site/assets/banners")===3);
check("배너 3장 폴백",[1,2,3].every(n=>html.includes(`home-hero-0${n}.webp`)));
check("배너 3초 자동재생",html.includes("state.bannerTimer = setInterval")&&html.includes("}, 3000)")&&html.includes('heroAutoplay = "running"'));
check("과일 아이콘 21개",countFiles("site/assets/fruit-icons")===21);
check("과일 아이콘 매핑",html.includes("FRUITMARKET_FRUIT_ICON_FILES=Object.freeze"));
check("브랜드 자산",countFiles("site/assets/brand")===2);
check("UI 아이콘",countFiles("site/assets/ui-icons")===18);
check("Supabase 설정 선로딩",html.indexOf("./config/supabase-config.js")>=0&&html.indexOf("./config/supabase-config.js")<html.indexOf("production-api-config"));
check("Supabase 단일 어댑터",html.includes("./assets/js/supabase-adapter.js")&&adapter.includes("Object.defineProperty(global, \"FruitMarketApi\""));
check("기존 API 덮어쓰기 방지",adapter.includes("legacyApiAtBoot")&&adapter.includes("configurable: false"));
check("UUID 별칭 브리지",adapter.includes("uuidToAlias")&&adapter.includes("backendPath")&&adapter.includes("FruitMarketIds"));
check("회원가입 약관 원장",adapter.includes("consentReceipts")&&adapter.includes("AGE_CONFIRM"));
check("카카오 OAuth",adapter.includes('provider: "kakao"'));
check("비밀번호 재설정",ui.includes("resetPassword")&&adapter.includes("auth-callback.html"));
check("관리자 MFA",ui.includes("enrollMfa")&&ui.includes("verifyMfa"));
check("Toss v2 SDK",html.includes("https://js.tosspayments.com/v2/standard"));
check("결제 서버 승인",adapter.includes('invoke("payment-confirm"')&&paymentConfirm.includes("finalize_payment"));
check("환불 서버 처리",adapter.includes('invoke("payment-cancel"')&&paymentCancel.includes("apply_payment_refund"));
check("정산 실제 지급대행",adapter.includes('invoke("payout-run"')&&payout.includes("PAYOUT_PROVIDER_NOT_CONFIGURED"));
check("결제 비밀키 프론트 미포함",!/(test_sk_|live_sk_|TOSS_SECRET_KEY\s*=|SUPABASE_SERVICE_ROLE_KEY\s*=|SUPABASE_SECRET_KEY\s*=)/.test([html,adapter,config].join("\n")));
check("빌드 비밀키 차단",build.includes("service_role")&&build.includes("SUPABASE_SECRET_KEY")&&build.includes("TOSS_SECRET_KEY"));
check("결제 기본 비활성",config.includes("paymentsEnabled: false")&&config.includes('tossClientKey: ""'));
check("원본 데모 결제 제거",!html.includes("STATIC_DEMO")&&!html.includes("mockDB")&&!html.includes("fakePayment"));
check("사업자번호",html.includes("571-31-01733"));
check("Part46 기반 UI 유지",html.includes("./assets/js/marketplace-platform-ui.js")&&marketplaceUi.includes("FruitMarketSafeAction"));
check("과일 신선정보 UI",marketplaceUi.includes("fresh-profile")&&marketplaceUi.includes("inventory/lots"));
check("분쟁 처리 UI",marketplaceUi.includes("/api/mypage/disputes")&&marketplaceUi.includes("/api/admin/disputes"));
check("법적 중개 고지",marketplaceUi.includes("판매주체")&&marketplaceUi.includes("통신판매중개"));
check("버튼 중복 실행 차단",marketplaceUi.includes("pending.has(button)")&&marketplaceUi.includes('aria-busy'));

check("Part48 상호보호 UI 로드",html.includes("./assets/js/mutual-protection-ui.js")&&protectionUi.includes('const VERSION = "48.0.0"'));
check("소비자 신고·이의제기 UI",protectionUi.includes("fm48-buyer-protection")&&protectionUi.includes("/api/mypage/trust-reports")&&protectionUi.includes("/api/mypage/trust-appeals"));
check("판매자 구매자악용 신고·반품검수 UI",protectionUi.includes("fm48-seller-protection")&&protectionUi.includes("/api/seller/trust-reports")&&protectionUi.includes("/api/seller/return-inspections"));
check("관리자 수동심사 UI",protectionUi.includes("fm48-admin-protection")&&protectionUi.includes("수동심사와 서로 다른 관리자 2인 승인을 거친 최종 계정 제한")&&protectionUi.includes("/api/admin/trust/cases"));
check("양측 주장만으로 최종제한 금지 고지",protectionUi.includes("어느 한쪽의 주장만으로")&&protectionUi.includes("자동최종결정"));
check("Part48 API 경로",["/api/mypage/trust-protection","/api/seller/trust-protection","/api/admin/trust/dashboard","/api/admin/trust/cases","/api/admin/trust/appeals"].every(x=>api.includes(x)));
check("위험신호는 수동심사 보조",protectionSql.includes("final_action_requires_manual_review")&&protectionSql.includes("automatic_final_decision boolean not null default false"));
check("판매자 위험규칙",["SELLER_FALSE_TRACKING","SELLER_NON_SHIPMENT_CLUSTER","SELLER_RECALL_OR_UNSAFE_LOT","SELLER_PAYOUT_ACCOUNT_CHANGE"].every(x=>protectionSql.includes(x)));
check("구매자 위험규칙",["BUYER_REFUND_VELOCITY","BUYER_EMPTY_OR_SWITCH_RETURN","BUYER_DUPLICATE_REFUND","BUYER_FALSE_NONDELIVERY"].every(x=>protectionSql.includes(x)));
check("정산계좌 72시간 냉각",protectionSql.includes("interval '72 hours'")&&protectionSql.includes("SETTLEMENT_ACCOUNT_CHANGED"));
check("증거 무결성",protectionSql.includes("TRUST_EVIDENCE_IMMUTABLE")&&protectionSql.includes("prevent_evidence_mutation"));
check("이의제기 구조",protectionSql.includes("create table if not exists public.trust_appeals")&&protectionSql.includes("submit_trust_appeal"));
check("내부 보안함수 직접 RPC 차단",protectionSql.includes("revoke execute on function public.recalculate_entity_trust")&&protectionSql.includes("from public,anon,authenticated"));
check("최종 계정제한 관리자 2인 승인",protectionSql.includes("trust_case_decision_approvals")&&protectionSql.includes("v_approval_count<2")&&protectionUi.includes("서로 다른 관리자 2인 승인"));
check("허위신고 반복 위험규칙",protectionSql.includes("BUYER_FALSE_REPORT_PATTERN")&&protectionSql.includes("SELLER_FALSE_REPORT_PATTERN"));
check("신고 권한·일일횟수 제한",api.includes("ORDER_SELLER_RELATION_FORBIDDEN")&&api.includes("CLAIM_ORDER_RELATION_FORBIDDEN")&&api.includes("TRUST_REPORT_DAILY_LIMIT"));
check("임시조치 자동만료",protectionSql.includes("status='EXPIRED'")&&protectionSql.includes("ends_at<=now()"));
check("결제 전 위험검토",checkout.includes("assess_checkout_risk")&&checkout.includes("CHECKOUT_MANUAL_REVIEW_REQUIRED"));
check("중복환불 차단·정상환불 계속",paymentCancel.includes("assess_refund_risk")&&paymentCancel.includes("DUPLICATE_BLOCK")&&paymentCancel.includes("apply_payment_refund"));
check("지급 전 위험검토",payout.includes("assess_payout_risk")&&payout.includes("PAYOUT_RISK_REVIEW_REQUIRED"));
check("정기 통제 실행",scheduled.includes("run_mutual_protection_controls"));
check("공개 신뢰안전 정책",exists("site/policies/trust-safety.html")&&trustPolicy.includes("최종 불이익을 자동 확정하지 않습니다")&&html.includes("/policies/trust-safety.html"));
check("약관 균형보호",terms.includes("소비자 부정행위")&&terms.includes("판매자 부정행위")&&terms.includes("고의·중대한 과실"));
check("판매자 정책 보호",sellerPolicy.includes("소비자 악용")&&sellerPolicy.includes("반품 검수")&&sellerPolicy.includes("정산계좌"));
check("환불 정책 증거·이의제기",commerce.includes("증빙")&&commerce.includes("이의제기")&&commerce.includes("중복환불"));
check("개인정보 최소화·오탐방지",privacy.includes("해시 신호")&&privacy.includes("동일 주소")&&privacy.includes("자동 확정하지 않으며"));
check("정책 v2 원문해시 등록",["BUYER_TERMS","PRIVACY_POLICY","COMMERCE_POLICY","SELLER_TERMS","TRUST_SAFETY_POLICY"].every(x=>protectionSql.includes(x))&&!protectionSql.includes("REPLACE_WITH_BUILD_HASH"));
check("상호보호 정책 sitemap",read("site/sitemap.xml").includes("/policies/trust-safety.html"));

const result={version:"48.0.0",checkedAt:new Date().toISOString(),checks,failures,passed:failures.length===0};
fs.mkdirSync(path.join(root,"tests"),{recursive:true});
fs.writeFileSync(path.join(root,"tests/static-check-results.json"),JSON.stringify(result,null,2));
console.log(JSON.stringify(result,null,2));
process.exit(result.passed?0:1);
